FROM gcc:11

RUN apt-get update\
    && apt-get install -y \
    cmake \
    git \
    libbenchmark-dev

#RUN git clone https://github.com/google/benchmark.git
#RUN cd benchmark && cmake -E make_directory "build" && cmake -DCMAKE_BUILD_TYPE=Release -S . -B "build"
#RUN cmake --build "build" --config Release
